CLASS LHC_ZZLIR_LIB_BOOK_MNT_0303 DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
        IMPORTING
           REQUEST requested_authorizations FOR ZzlirLibBookMnt0303
        RESULT result.
ENDCLASS.

CLASS LHC_ZZLIR_LIB_BOOK_MNT_0303 IMPLEMENTATION.
  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.
ENDCLASS.
